name: push-workflow
on: push

jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo hello world234324324324
    - name: step2
      run: |
        echo hello world
        echo github action
        